---
title: "ggplot2 Tutorial - Overview Figures"
author: "Cedric"
date: "16 8 2019"
output: html_document
---

```{r set options, include = F}
options(width = 700)
knitr::opts_chunk$set(warning = F, message = F, out.width = "100%")
```
  
```{r setup, warning = F}
library(tidyverse)
chic <- readr::read_csv("https://raw.githubusercontent.com/Z3tt/R-Tutorials/master/ggplot2/chicago-nmmaps.csv")
```


```{r origin-force}
(p1 <- chic %>% 
  dplyr::filter(temp > 25, o3 > 20) %>% 
  ggplot(aes(x = temp, y = o3)) + 
    geom_point(alpha = 0.7) + 
    labs(x = expression(paste("Temperature higher than 25 ", degree ~ F, "")), 
         y = "Ozone higher than 20 ppb") + 
    expand_limits(x = 0, y = 0) + 
    scale_x_continuous(expand = c(0, 0)) + 
    scale_y_continuous(expand = c(0, 0)) +
    coord_cartesian(clip = "off"))
```

```{r extrafont, eval = c(1, 2), message = F}
library(extrafont)
extrafont::loadfonts(device = "win")

(p2 <- ggplot(chic, aes(x = date, y = temp)) +
  geom_point(color = "firebrick", alpha = 0.5) + 
  labs(x = "Year", y = "Temperature", title = "Temperatures in Chicago") +
  scale_y_continuous(label = function(x) {return(paste(x, "°F"))}) + 
  theme_bw(base_size = 12, base_family = "Roboto Condensed") +
  theme(plot.title = element_text(size = 15, family = "Poppins ExtraBold", 
                                  face = "bold", color = "firebrick", 
                                  margin = margin(0, 0, 0, 0))))
```

```{r legend-order}
chic$season <- factor(chic$season, levels = c("Spring", "Summer", 
                                              "Autumn", "Winter"))

(p3 <- ggplot(chic, aes(x = date, y = temp, color = factor(season))) +
  geom_point() +
  geom_rug(show.legend = F) +
  labs(x = "Year", y = "Temperature (°F)") + 
  theme_light(base_size = 12, base_family = "Roboto Condensed") +
  theme(legend.title = element_text(color = "chocolate", 
                                    size = 14, face = 2),
        legend.key = element_rect(fill = "transparent")) +
  scale_color_discrete("Seasons:", labels = c("Mar - May", "Jun - Aug", 
                                              "Sep - Nov", "Dec - Feb")) +
  guides(color = guide_legend(override.aes = list(size = 3))))
```

```{r legend-manual}
(p4 <- ggplot(chic, aes(x = date, y = o3)) + 
  geom_line(aes(color = "line")) +  
  geom_point(aes(color = "points")) +
  labs(x = "Year", y = "Ozone") +
  scale_color_manual("", guide = "legend", 
                     values = c("points" = "darkorange2", 
                                "line" = "grey80")) +
  guides(color = guide_legend(override.aes = list(linetype = c(1, 0), 
                                                  shape = c(NA, 16)))) +
  theme_light(base_size = 14, base_family = "Roboto Condensed") +
  theme(panel.grid = element_blank()))
```

```{r wrap-plots-1-row}
(p5 <- ggplot(chic, aes(x = date, y = temp)) +
   geom_point(color = "chartreuse4", alpha = 0.3) +
   labs(x = "Year", y = "Temperature (°F)") + 
   facet_grid( ~ season) +
   theme_linedraw(base_size = 12, base_family = "Roboto Condensed") +
   theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
         panel.grid = element_blank()))
```

```{r Economist}
library(ggthemes)

(p6 <- ggplot(chic, aes(x = date, y = temp, color = factor(season))) +
  geom_point() +
  labs(x = "Year", y = "Temperature (°F)") + 
  ggtitle("Ups and Downs of Chicago's Daily Temperatures") +
  theme_economist(base_size = 9) + 
  scale_color_economist(name = "Seasons:") +
  theme(legend.title = element_text(size = 8, face = "bold"),
        legend.text = element_text(size = 8),
        legend.position = "bottom"))
```

```{r Tufte}
set.seed(2019)
chic.red <- chic[sample(nrow(chic), 50), ]

(p7 <- ggplot(chic.red, aes(x = temp, y = o3)) +
  geom_point() +
  labs(x = "Temperature (°F)", y = "Ozone") + 
  ggtitle("Temperature and Ozone Levels in Chicago") +
  theme_tufte() +
  stat_smooth(method = "lm", col = "black", size = 0.7, 
              fill = "gray60", alpha = 0.2))
```


```{r viridis-continuous}
library(viridis)

(p8 <- ggplot(chic, aes(x = date, y = temp, color = o3)) + 
   geom_point() + 
   labs(x = "Year", y = "Temperature (°F)", title = "Viridis 'inferno'") + 
   theme_minimal(base_size = 12, base_family = "Roboto Condensed") +
   scale_color_viridis(option = "inferno", "Ozone:"))
```


```{r ggrepel}
library(ggrepel)

set.seed(1)

sample <- chic %>% 
  dplyr::group_by(season) %>% 
  dplyr::sample_frac(0.01)

(p9 <- ggplot(chic, aes(x = date, y = temp, label = season)) +
  geom_point(alpha = 0.5) +
  geom_point(data = sample, aes(color = factor(temp)), size = 2.5) +
  geom_label_repel(data = sample, aes(fill = factor(temp)), 
                   color = "white", fontface = "bold") +
  theme_bw(base_size = 12, base_family = "Roboto Condensed") +
  labs(x = "Year", y = "Temperature (°F)") +
  theme(legend.position = "none"))
```

```{r grobTree-scales-free}
library(grid)

my_grob <- grobTree(textGrob("This text stays in place!", 
                             x = 0.1, y = 0.9, hjust = 0, 
                             gp = gpar(col = "black", 
                                       fontsize = 10, 
                                       fontface = "bold")))

(p10 <- ggplot(chic, aes(x = temp, y = o3)) +
  geom_point(color = "tan") + 
  labs(x = "Temperature (°F)", y ="Ozone") +
  facet_wrap(~ season, scales = "free") +
  theme_bw(base_size = 12, base_family = "Roboto Condensed") +
  annotation_custom(my_grob))
```

```{r flip-coords}
(p11 <- ggplot(chic, aes(x = season, y = o3)) +
  geom_boxplot(fill = "indianred") + 
  labs(x = "Season", y = "Ozone") +
  coord_flip() +
  theme_bw(base_size = 12, base_family = "Roboto Condensed"))
```

```{r pie-chart}
(p12 <- chic %>% 
  dplyr::mutate(o3_avg = median(o3)) %>% 
  dplyr::filter(o3 > o3_avg) %>% 
  dplyr::mutate(n_all = n()) %>% 
  dplyr::group_by(season) %>% 
  dplyr::summarize(rel = n() / unique(n_all)) %>% 
  ggplot(aes(x = "", y = rel)) +
    geom_col(aes(fill = factor(season)), width = 1) + 
    labs(x = "", 
         y = "Proportion of Days Exceeding\nthe Median Ozone Level") +
    coord_polar("y") +
    scale_fill_brewer(palette = "Set1", name = "Season:") +
    theme_minimal(base_size = 12, base_family = "Roboto Condensed") +
    theme(axis.ticks = element_blank(),
          panel.grid = element_blank()))
```

```{r jitter}
(p13 <- ggplot(chic, aes(x = season, y = o3)) + 
  labs(x = "Season", y = "Ozone") + geom_jitter(aes(color = season), alpha = 0.25, 
       position = position_jitter(width = 0.3)) +
  theme_light(base_size = 12, base_family = "Roboto Condensed") +
  theme(legend.position = "none",
        panel.grid = element_blank()))
```

```{r violin-jitter-box, fig.height = 6}
(p14 <- ggplot(chic, aes(x = season, y = o3)) + 
  labs(x = "Season", y = "Ozone") + 
    geom_violin(aes(fill = season), color = "transparent", alpha = 0.5) +
    geom_boxplot(outlier.alpha = 0, coef = 0, 
                 color = "gray40", width = 0.1) +
    theme_light(base_size = 12, base_family = "Roboto Condensed") +
    theme(legend.position = "none",
          panel.grid = element_blank()) +
    coord_flip())
```

```{r corr-matrix}
corm <- round(cor(chic[ , sort(c("death", "temp", "dewpoint", "pm10", "o3"))], 
                  method = "pearson", use = "pairwise.complete.obs"), 2)
corm[lower.tri(corm)] <- NA

library(reshape2)

corm <- melt(corm)
corm$Var1 <- as.character(corm$Var1)
corm$Var2 <- as.character(corm$Var2)
corm <- na.omit(corm)
head(corm, 10)

(p15 <- ggplot(corm, aes(x = Var2, y = Var1)) +
   geom_tile(data = corm, aes(fill = value), color = "white") +
   labs(x = "Variable 2", y = "Variable 1") +
   scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                        midpoint = 0, limit = c(-1, 1), 
                        name = "Correlation\n(Pearson)") +
   theme_bw(base_size = 12, base_family = "Roboto Condensed") +
   theme(axis.text.x = element_text(angle = 45, size = 11, 
                                    vjust = 1, hjust = 1)) +
   coord_equal())
```

### Create a Contour Plot

Contour plots are s nice way to display three-dimensional data by indicating die thresholds of values. Here, we are going to plot the dew point (i.e. [the temperature at which airborne water vapor will condense to form liquid dew](https://en.wikipedia.org/wiki/Dew_point)) related to temperature and ozone levels:

```{r contour}
## interpolate data
library(akima)
fld <- with(chic, interp(x = temp, y = o3, z = dewpoint))

## prepare data in long format
library(reshape2)
df <- melt(fld$z, na.rm = T)
names(df) <- c("x", "y", "Dewpoint")
df$Temperature <- fld$x[df$x]
df$Ozone <- fld$y[df$y]

(p16 <- ggplot(data = df, aes(x = Temperature, y = Ozone, z = Dewpoint)) +
  geom_tile(aes(fill = Dewpoint)) + 
  stat_contour(color = "white", size = 0.7, bins = 5) + 
  scale_fill_viridis(name = "Dewpoint:") +
  theme_bw(base_size = 12, base_family = "Roboto Condensed") +
  theme(panel.background = element_rect(fill = "white"),
        panel.border = element_rect(color = "black", fill = NA),
        legend.title = element_text(size = 15),
        axis.text = element_text(size = 12),
        axis.title.x = element_text(size = 15, vjust = -0.5),
        axis.title.y = element_text(size = 15, vjust = 0.2),
        legend.text = element_text(size = 12)))
```

```{r}
library(ggridges)

(p17 <- ggplot(chic, aes(x = temp, y = factor(year), fill = year)) + 
  geom_density_ridges(stat = "binline", bins = 25, scale = 0.9, 
                      draw_baseline = F, show.legend = F) + 
  labs(x = "Temperature (°F)", y = "Season") +
  theme_minimal(base_family = "Roboto Condensed"))
```

```{r ridges-groups}
(p18 <- ggplot(data = filter(chic, season %in% c("Summer", "Winter")), 
         aes(x = temp, y = year, fill = paste(year, season))) +
  geom_density_ridges(alpha = 0.7, rel_min_height = 0.01, 
                      color = "white", from = -5, to = 95) +
  scale_fill_cyclical(breaks = c("1997 Summer", "1997 Winter"),
                      labels = c(`1997 Summer` = "Summer", 
                                 `1997 Winter` = "Winter"),
                      values = c("tomato", "dodgerblue"),
                      name = "Season:", guide = "legend") +
  theme_ridges(font_family = "Roboto Condensed", grid = F) + 
  labs(x = "Temperature (°F)", y = "Year"))
```

```{r geom-ribbon-range}
chic$o3run <- as.numeric(stats::filter(chic$o3, rep(1/30, 30), sides = 2))

chic$mino3 <- chic$o3run - sd(chic$o3run, na.rm = T)
chic$maxo3 <- chic$o3run + sd(chic$o3run, na.rm = T)

(p19 <- ggplot(chic, aes(x = date, y = o3run)) +
   geom_ribbon(aes(ymin = mino3, ymax = maxo3), alpha = 0.5, 
               fill = "darkseagreen3", color = "transparent") +
   geom_line(color = "aquamarine4", lwd = 0.7) +
   labs(x = "Year", y = "Temperature (°F)") +
   theme_light(base_size = 12, base_family = "Roboto Condensed"))
```

```{r GAM-spec}
(p20 <- ggplot(chic, aes(x = date, y = temp)) + 
   geom_point(color = "gray40", alpha = 0.3) +
   labs(x = "Year", y = "Temperature (°F)") +
   stat_smooth(method = "gam", formula = y ~ s(x, k = 1000), 
               se = F, size = 1.2, aes(col = "1000")) +
   stat_smooth(method = "gam", formula = y ~ s(x, k = 100), 
               se = F, size = 1, aes(col = "100")) +
   stat_smooth(method = "gam", formula = y ~ s(x, k = 10), 
               se = F, size = 0.8, aes(col = "10")) +
   scale_color_manual(name = "k", values = c("darkorange1", 
                                             "firebrick", 
                                             "dodgerblue3")) +
   theme_bw(base_size = 12, base_family = "Roboto Condensed"))
```

```{r full-panel}
library(patchwork)

{p1 + p3 + p5 + p4 + p10 + plot_layout(ncol = 5)} / 
  {p6 + p7 + p8 + p13 + p2 + plot_layout(ncol = 5)} /
  {p11 + p9 + p18 + p19 + p15 + plot_layout(ncol = 5)} /
  {p16 + p17 + p14 + p12 + p20 + plot_layout(ncol = 5)}
  
ggsave("./img/overview.png", width = 30, height = 18)
```

```{r full-panel}
library(patchwork)

(p1 + p3 + p5 + p4 + p10) + 
  (p6 + p7 + p8 + p13 + p2) +
  (p11 + p9 + p18 + p19 + p15) +
  (p16 + p17 + p14 + p12 + p20) + plot_layout(ncol = 5)
  
ggsave("panel_pw.png", width = 30, height = 20)
```
